### ISSUE TITLE
Create Nuget Package of Base Classes and Tools

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/dotnet-api-template#5]
### Issue description
A lot of what this template has is the base classes and tools used by all microservices. We copy/paste and they do not get updated by hand. Also it skews our code coverage for the various services because we have to test the common code. We originally did not create a package for this because we did not have a package repository. Github Repositories can now act as that nuget repository.

The shared projects should be:
* NCI.OCPL.Api.Common
* NCI.OCPL.Api.Common.Testing

There should also be tests for those packages, which it looks like there are none for in this template.

> **ESTIMATE** TBD

### What's the expected change?
- The various shared code modules are pulled out into their own repo and a nuget reference to that package is added to this template.

### What's the current functionality?
- N/A

### What's the updated acceptance criteria?
N/A

**Comment by VictoriaSunNIH** [comment]
About 2 weeks of work - starting ... @blairlearn

**Comment by santwuma** [comment]
Initial rollout to target elastic search 5.6.

**Comment by blairlearn** [comment]
Rolled into #9
